updating cli

diff --git a/bin/dbwebb b/bin/dbwebb
--- a/bin/dbwebb
+++ b/bin/dbwebb
@@ -1,7 +1,5 @@
 #!/bin/sh
-
 VERSION="1.0.0"
-BASEDIR="dbwebb-kurser"
 
 
 
@@ -13,11 +11,15 @@ printUsage()
     echo
     echo "Utility dbwebb $VERSION by Mikael Roos, to upload, verify and publish course results when done."
     echo
-    echo "Usage: dbwebb command user host"
+    echo "Usage: dbwebb [options] <command> [arguments]"
     echo
-    echo "Command can be any of the following:"
+    echo "Options:"
     echo 
-    echo "  help      Print this message."
+    echo "  -h         Print this message and exit."
+    echo "  -y         Do not wait for my input, just proceed."
+    echo
+    echo "Command:"
+    echo 
     echo "  test      Test the connection by loggin in."
     echo "  login     Login to the server using ssh."
     echo "  init      Init the remote server and create a destination directory."
@@ -26,6 +28,16 @@ printUsage()
     echo "  validate  Upload your files and validate that your results passes automatic tests."
     echo "  publish   Upload, Validate and Publish your course results to the web."
     echo
+    echo "Example:"
+    echo 
+    echo "  $ dbwebb test"
+    echo "  $ dbwebb login"
+    echo "  $ dbwebb init"
+    echo "  $ dbwebb sshkey"
+    echo "  $ dbwebb upload"
+    echo "  $ dbwebb -y validate kmom01"
+    echo "  $ dbwebb -y publish all"
+    echo 
     exit
 }
 
@@ -37,14 +49,18 @@ printUsage()
 executeCommand()
 {
     INTRO=$1
-    echo "\n$INTRO"
-    echo -n "Press a key to continue..."
-    read void
+
+    if [ $SKIP_READLINE = "no" ]
+    then
+        echo "\n$INTRO"
+        echo -n "Press a key to continue..."
+        read void
+    fi
     
     COMMAND=$2
     echo "\nExecuting command:"
-    echo "-----------------------------------------"
     echo "$COMMAND"
+    echo "-----------------------------------------"
     
     sh -c "$COMMAND"
     STATUS=$?
@@ -68,7 +84,7 @@ executeCommand()
 testConnection()
 {
     INTRO="I will now try to establish a connection with the server by loggin in to it."
-    COMMAND="ssh $1@$2 cat /etc/motd"
+    COMMAND="ssh ${USER}@${HOST} cat /etc/motd"
     MESSAGE="SUCCESS to establish the connection."
     executeCommand "$INTRO" "$COMMAND" "$MESSAGE"
 }
@@ -81,7 +97,7 @@ testConnection()
 loginToServer()
 {
     INTRO="I will now try to establish a connection with the server by loggin in to it."
-    COMMAND="ssh $1@$2"
+    COMMAND="ssh ${USER}@${HOST}"
     MESSAGE="to establish the connection."
     executeCommand "$INTRO" "$COMMAND" "$MESSAGE"
 }
@@ -94,7 +110,7 @@ loginToServer()
 initServer()
 {
     INTRO="I will now try to init the remote server and create a directory where all uploaded files will reside."
-    COMMAND="ssh $1@$2 sh -c \"if [ ! -d dbwebb-kurser ]; then mkdir dbwebb-kurser; fi; chmod 700 dbwebb-kurser\""
+    COMMAND="ssh ${USER}@${HOST} 'sh -c \"if [ ! -d dbwebb-kurser ]; then mkdir dbwebb-kurser; fi; chmod 700 dbwebb-kurser; ls -l dbwebb-kurser\"'"
     MESSAGE="to init the server."
     executeCommand "$INTRO" "$COMMAND" "$MESSAGE"
 }
@@ -112,7 +128,7 @@ installSshKeys()
     executeCommand "$INTRO" "$COMMAND" "$MESSAGE"
 
     INTRO="I will now install the ssh-key at the remote server."
-    COMMAND="cat $HOME/.ssh/id_dsa.pub | ssh $1@$2 'cat >> .ssh/authorized_keys'"
+    COMMAND="cat $HOME/.ssh/id_dsa.pub | ssh $USER@$HOST 'cat >> .ssh/authorized_keys'"
     MESSAGE="to install the ssh-keys."
     executeCommand "$INTRO" "$COMMAND" "$MESSAGE"
 }
@@ -124,10 +140,6 @@ installSshKeys()
 #
 uploadToServer()
 {
-    PROJECT=${PWD##*/}
-    SOURCE="$PWD/"
-    DESTINATION="$1@$2:$BASEDIR/$PROJECT/"
-
     INTRO="Your current working directory will now be synced to remote server."
     COMMAND="rsync -av --exclude literature --exclude .git -e ssh $SOURCE $DESTINATION" 
     MESSAGE="to upload data."
@@ -141,12 +153,8 @@ uploadToServer()
 #
 validateUploadedResults()
 {
-    PROJECT=${PWD##*/}
-    SOURCE="$PWD/"
-    DESTINATION="$1@$2:$BASEDIR/$PROJECT/"
-
     INTRO="I will now try to init the remote server and create a directory where all uploaded files will reside."
-    COMMAND="ssh $1@$2 'cd $BASEDIR/$PROJECT; bin/dbwebb-validate all'"
+    COMMAND="ssh ${USER}@${HOST} 'cd $BASEDIR/$PROJECT; bin/dbwebb-validate all'"
     MESSAGE="to validate course results."
     executeCommand "$INTRO" "$COMMAND" "$MESSAGE"
 }
@@ -158,12 +166,8 @@ validateUploadedResults()
 #
 publishResults()
 {
-    PROJECT=${PWD##*/}
-    SOURCE="$PWD/"
-    DESTINATION="$1@$2:$BASEDIR/$PROJECT/"
-
     INTRO="I will now try to init the remote server and create a directory where all uploaded files will reside."
-    COMMAND="ssh $1@$2 'cd $BASEDIR/$PROJECT; bin/dbwebb-validate all'"
+    COMMAND="ssh ${USER}@${HOST} 'cd $BASEDIR/$PROJECT; bin/dbwebb-validate all'"
     MESSAGE="to validate and publish all course results."
     executeCommand "$INTRO" "$COMMAND" "$MESSAGE"
 }
@@ -173,43 +177,72 @@ publishResults()
 #
 # Main
 #
-if [ $# != 3 ]
+if [ $# -lt 1 ]
 then
     printUsage
 fi
 
-CMD=$1
-USER=$2
-HOST=$3
+# Get settings from config-file
+. bin/dbwebb-config
 
+
+# Get options
+SKIP_READLINE=no
+
+while getopts ":hy" opt
+do
+    case $opt in
+        (h) 
+            printUsage
+            ;;
+
+        (y) 
+            SKIP_READLINE=yes
+            ;;
+
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            echo 
+            echo "Use the following to get help."
+            echo "dbwebb -h"
+            echo
+            exit 1
+            ;;
+    esac
+done
+shift $((OPTIND - 1))
+
+
+# Execute command
+CMD=$1
 case $CMD in
     
     test)
-        testConnection $USER $HOST 
+        testConnection 
         ;;
 
     login)
-        loginToServer $USER $HOST
+        loginToServer 
         ;;
 
     init)
-        initServer $USER $HOST
+        initServer 
         ;;
 
     sshkey)
-        installSshKeys $USER $HOST
+        installSshKeys 
         ;;
 
     upload)
-        uploadToServer $USER $HOST
+        uploadToServer 
         ;;
 
     validate)
-        validateUploadedResults $USER $HOST
+        validateUploadedResults 
         ;;
 
     publish)
-        publishResults $USER $HOST
+        publishResults 
         ;;
 
     *)
