updating cli

diff --git a/bin/dbwebb-validate b/bin/dbwebb-validate
--- a/bin/dbwebb-validate
+++ b/bin/dbwebb-validate
@@ -1,16 +1,21 @@
 #!/bin/sh
 
 VERSION="1.0.0"
-BASEDIR="dbwebb-kurser"
-TARGET="$PWD/me"
-BUILD1="$HOME/www"
-BUILD2="$BUILD1/dbwebb"
-BUILD="$BUILD2/javascript1"
+
 TESTS=0
 ASSERTS=0
 FAULTS=0
 
-HTML_MINIFIER="html-minifier --minify-js --minify-css --use-short-doctype --remove-attribute-quotes --collapse-boolean-attributes --conservative-collapse --collapse-whitespace --remove-comments"
+
+#
+# External tools
+#
+JSHINT="jshint"
+
+HTMLHINT="htmlhint"
+
+HTML_MINIFIER="html-minifier"
+HTML_MINIFIER_OPTIONS="--minify-js --minify-css --use-short-doctype --remove-attribute-quotes --collapse-boolean-attributes --conservative-collapse --collapse-whitespace --remove-comments"
 
 UGLIFYJS="uglifyjs"
 UGLIFYJS_OPTIONS="-m -c --screw-ie8 --comments"
@@ -38,8 +43,11 @@ printUsage()
     echo
     echo "Options:"
     echo 
-    echo "  -h, --help         Print this message and exit."
-    echo "  -n, --no-publish   Only validate, do not publish."
+    echo "  -h         Print this message and exit."
+    echo "  -i         Ignore any faults and proceed anyway."
+    echo "  -n         Only validate, do not publish."
+    echo "  -r         Print required external commands."
+    echo "  -v         Print version and exit."
     echo 
     echo "Item:"
     echo 
@@ -55,7 +63,7 @@ printUsage()
     echo "Example:"
     echo 
     echo "  $ dbwebb-validate kmom01"
-    echo "  $ dbwebb-validate --no-publish kmom01"
+    echo "  $ dbwebb-validate -n kmom01"
     echo 
     exit
 }
@@ -78,6 +86,9 @@ assert()
     then
         FAULTS=$(( $FAULTS + 1 ))
         echo "FAILED. $MESSAGE\n"
+
+        [ $IGNORE_FAULTS = "no" ] || return  
+
         echo "Tests: $TESTS Asserts: $ASSERTS Faults: $FAULTS\n"
         echo "Correct the fault and run the validation again.\n\n"
         exit 1
@@ -87,10 +98,55 @@ assert()
 
 
 #
+# Check for installed commands
+#
+checkCommand()
+{
+    COMMAND=$1
+    echo "Checking $COMMAND"
+
+    if ! hash $COMMAND 2>/dev/null
+    then
+        echo >&2 "I require $COMMAND but it's not installed. Aborting."
+        echo >&2 "Use the following command to see what is required to run this script"
+        echo >&2 "  dbwebb-validate -r";
+        exit 1
+    fi
+}
+
+
+
+#
+# Check for installed tools
+#
+CHECKTOOLS="no"
+checkTools()
+{
+    [ $CHECKTOOLS = "no" ] || return; CHECKTOOLS="yes"
+
+    echo "Check for installed tools."
+
+    checkCommand $JSHINT
+    checkCommand $HTMLHINT
+
+    [ $PUBLISH = "yes" ] || return
+
+    checkCommand $HTML_MINIFIER
+    checkCommand $UGLIFYJS
+    checkCommand $CLEANCSS
+}
+
+
+
+#
 # Init the build directory
 #
+BUILDDIR="no"
 initBuildDir()
 {
+    [ $BUILDDIR = "no" ] || return; BUILDDIR="yes"
+    [ $PUBLISH = "yes" ] || return
+
     echo "Init the build directory."
 
     if [ ! -d $BUILD1 ] 
@@ -114,18 +170,22 @@ initBuildDir()
 #
 # Test me/ at the beginning
 #
+MESTART="no"
 testMeStart()
 {
+    [ $MESTART = "no" ] || return; MESTART="yes"
+
     TESTS=$(( $TESTS + 1 ))
 
     echo "Testing Me-directory items."
 
-    rm -f $BUILD/me.html
-    
     assert 0 "[ -d $TARGET ]" "Missing directory for me-pages: $TARGET"
     assert 0 "[ -f $TARGET/me.html ]" "Missing presentation file: $TARGET/me.html"
 
+    [ $PUBLISH = "yes" ] || return
+
     rsync -a $TARGET/me.html $BUILD/
+    rsync -a --delete $TARGET/../example/ $BUILD/example/
 }
 
 
@@ -141,6 +201,8 @@ testKmom01()
     echo "Testing Kmom01 structure."
 
     assert 0 "[ -d $TARGET/$KMOM ]" "Missing directory: $TARGET/$KMOM"
+
+    [ $PUBLISH = "yes" ] || return
 
     if [ ! -d $BUILD/$KMOM ] 
     then
@@ -161,15 +223,19 @@ testKmom01Sandbox()
 
     echo "Testing Kmom01 Sandbox example."
 
-    rm -rf $BUILD/$KMOM/$DIR
-
     assert 0 "[ -d $TARGET/$KMOM/$DIR ]" "Missing directory: $TARGET/$KMOM/$DIR"
-    assert 0 "jshint $TARGET/$KMOM/$DIR/js/*.js" "JSHint failed testing JavaScript files."
-    assert 0 "bin/htmlhint $TARGET/$KMOM/$DIR/index.html" "HTMLHint failed testing HTML files."
+
+    FILE="$TARGET/$KMOM/$DIR/js/*.js"
+    assert 0 "$JSHINT $FILE" "JSHint failed testing JavaScript files:\n$FILE"
+
+    FILE="$TARGET/$KMOM/$DIR/index.html"
+    assert 0 "$HTMLHINT $FILE" "HTMLHint failed testing HTML files:\n$FILE"
+
+    [ $PUBLISH = "yes" ] || return
 
     rsync -a $TARGET/$KMOM/$DIR/ $BUILD/$KMOM/$DIR/
 
-    $HTML_MINIFIER $BUILD/$KMOM/$DIR/index.html --output $BUILD/$KMOM/$DIR/index.html
+    $HTML_MINIFIER $HTML_MINIFIER_OPTIONS $BUILD/$KMOM/$DIR/index.html --output $BUILD/$KMOM/$DIR/index.html
     
     $UGLIFYJS $BUILD/$KMOM/$DIR/js/main.js -o $BUILD/$KMOM/$DIR/js/main.js $UGLIFYJS_OPTIONS
     
@@ -184,6 +250,9 @@ testKmom01Sandbox()
 #
 kmom01()
 {
+    checkTools
+    initBuildDir
+    testMeStart
     testKmom01
     testKmom01Sandbox
 }
@@ -195,7 +264,9 @@ kmom01()
 #
 kmom02()
 {
-    pass
+    checkTools
+    initBuildDir
+    testMeStart
 }
 
 
@@ -205,7 +276,9 @@ kmom02()
 #
 kmom03()
 {
-    pass
+    checkTools
+    initBuildDir
+    testMeStart
 }
 
 
@@ -215,7 +288,9 @@ kmom03()
 #
 kmom04()
 {
-    pass
+    checkTools
+    initBuildDir
+    testMeStart
 }
 
 
@@ -225,7 +300,9 @@ kmom04()
 #
 kmom05()
 {
-    pass
+    checkTools
+    initBuildDir
+    testMeStart
 }
 
 
@@ -235,7 +312,9 @@ kmom05()
 #
 kmom06()
 {
-    pass
+    checkTools
+    initBuildDir
+    testMeStart
 }
 
 
@@ -245,7 +324,9 @@ kmom06()
 #
 kmom10()
 {
-    pass
+    checkTools
+    initBuildDir
+    testMeStart
 }
 
 
@@ -259,57 +340,87 @@ then
     #printUsage
 fi
 
-echo $0
+# Get settings from config-file
+. bin/dbwebb-config
 
+
+# Get options
+PUBLISH="yes"
+IGNORE_FAULTS="no"
+
+while getopts ":hinrv" opt
+do
+    case $opt in
+        (h) 
+            printUsage
+            ;;
+
+        (i) 
+            IGNORE_FAULTS="yes"
+            ;;
+
+        (n) 
+            PUBLISH="no"
+            ;;
+
+        (r) 
+            echo "Required external tools are:"
+            echo "  npm install jshint html-minifier uglify-js clean-css htmlhint"
+            echo
+            exit 0
+            ;;
+
+        (v) 
+            echo $VERSION
+            exit 0
+            ;;
+
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            echo 
+            echo "Use the following to get help."
+            echo "dbwebb-validate -h"
+            echo
+            exit 1
+            ;;
+    esac
+done
+shift $((OPTIND - 1))
+
+
+# Execute command
 CMD=$1
-
 case $CMD in
     
     kmom01)
-        initBuildDir
-        testMeStart
         kmom01
         ;;
 
     kmom02)
-        initBuildDir
-        testMeStart
         kmom02
         ;;
 
     kmom03)
-        initBuildDir
-        testMeStart
         kmom03
         ;;
 
     kmom04)
-        initBuildDir
-        testMeStart
         kmom04
         ;;
 
     kmom05)
-        initBuildDir
-        testMeStart
         kmom05
         ;;
 
     kmom06)
-        initBuildDir
-        testMeStart
         kmom06
         ;;
 
     kmom10)
-        initBuildDir
-        testMeStart
         kmom10
         ;;
 
     all)
-        initBuildDir
-        testMeStart
         kmom01
         kmom02
         kmom03
